name:                aoc-twenty
version:             0.1.0.0
github:              "thebruce/advent-of-code-2020"
license:             BSD3
author:              "Thomas Bruce"
maintainer:          "thomasmjbbruce@googlemail.com"
copyright:           "2020 Thomas Bruce"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A set of solutions for Advent of Code projects in Haskell

dependencies:
- base >= 4.7 && < 5
- directory
- optparse-applicative
- parser-combinators
- attoparsec
- containers
- text
- time
- mtl
- vector
- pointedlist

library:
  source-dirs: src
  default-extensions:
    - EmptyCase
    - FlexibleContexts
    - FlexibleInstances
    - InstanceSigs
    - MultiParamTypeClasses
    - LambdaCase
    - MultiWayIf
    - RecordWildCards
    - TupleSections
    - OverloadedStrings
    - ScopedTypeVariables
    - GADTs
    - NumericUnderscores
    - DeriveFunctor
    - DeriveFoldable

executables:
  aoc-twenty-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - EmptyCase
    - FlexibleContexts
    - FlexibleInstances
    - InstanceSigs
    - MultiParamTypeClasses
    - LambdaCase
    - MultiWayIf
    - RecordWildCards
    - TupleSections
    - OverloadedStrings
    - ScopedTypeVariables
    - GADTs
    - NumericUnderscores
    - DeriveFunctor
    - DeriveFoldable
    dependencies:
    - aoc-twenty
